"""Generate a corpus statistics report from parsed outputs.

Usage:
    python scripts/corpus_stats.py [--parsed corpus/parsed] [--out docs/corpus-stats.md]

Reads every ParsedDoc + chunk file under the parsed directory and writes a
markdown report: per-document table (pages, blocks, tables, chunks, sizes)
and corpus-level chunk-length distribution. Run after `python -m
datasheet_rag.ingest`; commit the report so corpus growth is reviewable in
diffs.
"""

from __future__ import annotations

import statistics
from pathlib import Path

import typer

from datasheet_rag.ingest.models import ParsedDoc, load_chunks

app = typer.Typer(add_completion=False)


def _dist_line(values: list[int]) -> str:
    qs = statistics.quantiles(values, n=4) if len(values) > 1 else [values[0]] * 3
    return (
        f"min {min(values)} · p25 {qs[0]:.0f} · median {qs[1]:.0f} · "
        f"p75 {qs[2]:.0f} · max {max(values)}"
    )


@app.command()
def main(
    parsed: Path = typer.Option(Path("corpus/parsed"), "--parsed"),
    out: Path = typer.Option(Path("docs/corpus-stats.md"), "--out"),
) -> None:
    doc_files = sorted(parsed.glob("*.json"))
    doc_files = [p for p in doc_files if not p.name.endswith("aliases.json")]
    if not doc_files:
        typer.echo("No parsed documents found — run `python -m datasheet_rag.ingest` first.")
        raise typer.Exit(1)

    rows: list[str] = []
    all_chunk_sizes: list[int] = []
    table_sizes: list[int] = []
    text_sizes: list[int] = []
    totals = {"pages": 0, "blocks": 0, "tables": 0, "chunks": 0}

    for doc_file in doc_files:
        doc = ParsedDoc.load(doc_file)
        chunks = load_chunks(doc_file.parent / f"{doc_file.stem}.chunks.jsonl")
        n_tables = sum(1 for b in doc.blocks if b.kind == "table")
        sizes = [c.n_chars for c in chunks]
        all_chunk_sizes.extend(sizes)
        table_sizes.extend(c.n_chars for c in chunks if c.kind == "table")
        text_sizes.extend(c.n_chars for c in chunks if c.kind == "text")
        totals["pages"] += doc.n_pages or 0
        totals["blocks"] += len(doc.blocks)
        totals["tables"] += n_tables
        totals["chunks"] += len(chunks)
        n_table_chunks = sum(1 for c in chunks if c.kind == "table")
        rows.append(
            f"| {doc.part} | {doc.manufacturer} | {doc.n_pages} | {len(doc.blocks)} | "
            f"{n_tables} | {len(chunks)} | {n_table_chunks} | {int(statistics.median(sizes))} |"
        )

    lines = [
        "# Corpus statistics",
        "",
        "Generated by `python scripts/corpus_stats.py` from `corpus/parsed/`.",
        "",
        "| Part | Mfr | Pages | Blocks | Table blocks | Chunks "
        "| Table chunks | Median chunk chars |",
        "|---|---|---|---|---|---|---|---|",
        *rows,
        f"| **TOTAL** | | **{totals['pages']}** | **{totals['blocks']}** | "
        f"**{totals['tables']}** | **{totals['chunks']}** | | |",
        "",
        "## Chunk-length distribution (chars)",
        "",
        f"- all chunks ({len(all_chunk_sizes)}): {_dist_line(all_chunk_sizes)}",
        f"- table chunks ({len(table_sizes)}): {_dist_line(table_sizes)}",
        f"- text chunks ({len(text_sizes)}): {_dist_line(text_sizes)}",
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")
    typer.echo(f"wrote {out} ({len(doc_files)} documents, {totals['chunks']} chunks)")


if __name__ == "__main__":
    app()
