"""Phase-2 smoke run: 20 qualitative questions through the full pipeline.

Usage:
    python scripts/smoke_run.py [--out docs/smoke-run.md] [--k 8]

Not an evaluation — no scoring, no gold answers. The output is a reviewable
markdown transcript: question, answer, citations, top retrieval hits.
Failure observations feed the Phase-3 golden set.
"""

from __future__ import annotations

import time
from pathlib import Path

import typer

QUESTIONS: list[tuple[str, str]] = [
    # (category, question)
    ("spec-lookup", "What is the typical input offset voltage of the OPA2993?"),
    ("spec-lookup", "What is the quiescent current of the TLV9062?"),
    ("spec-lookup", "What is the gain bandwidth product of the OPA188?"),
    ("spec-lookup", "What is the maximum output current of the LD1117?"),
    ("spec-lookup", "What is the resolution of the ADS1115 ADC?"),
    ("spec-lookup", "What is the accuracy of the TMP117 temperature sensor?"),
    ("conditions", "What is the dropout voltage of the NCP1117 at 800 mA?"),
    ("conditions", "What is the supply current of the SN65HVD230 in standby mode?"),
    ("conditions", "What is the OPA2993 input offset voltage drift over temperature?"),
    ("mcu", "How much flash memory does the STM32C031C4 have?"),
    ("mcu", "What is the maximum CPU frequency of the LPC1768?"),
    ("mcu", "How many USART interfaces does the STM32G071C8 provide?"),
    ("mcu", "What is the operating voltage range of the STM32F103RB?"),
    ("pinout", "What package options are available for the MCP3008?"),
    ("pinout", "How many channels does the TLV9064 have?"),
    ("comparison", "Compare the dropout voltage of the LD1117 and NCP1117 regulators"),
    ("comparison", "Which has more SRAM, the STM32C031C4 or the LPC1114?"),
    ("comparison", "Compare the input offset voltage of the OPA188 and OPA2188"),
    ("unanswerable", "What is the price of the OPA2993 in 1000-unit quantities?"),
    ("unanswerable", "What is the MTBF of the STM32C5A3ZG at 85°C?"),
]

app = typer.Typer(add_completion=False)


@app.command()
def main(
    out: Path = typer.Option(Path("docs/smoke-run.md"), "--out"),
    k: int = typer.Option(8, "--k"),
    model: str = typer.Option("qwen3:4b", "--model"),
) -> None:
    from datasheet_rag.rag.embed import NomicEmbedder
    from datasheet_rag.rag.generate import OllamaClient
    from datasheet_rag.rag.pipeline import ask
    from datasheet_rag.rag.retrieve import DenseRetriever
    from datasheet_rag.rag.store import ChunkStore

    retriever = DenseRetriever(ChunkStore(), NomicEmbedder())
    llm = OllamaClient(model=model)

    lines = [
        "# Smoke run — baseline RAG",
        "",
        f"Model: {model} · k={k} · dense retrieval · "
        "generated by scripts/smoke_run.py (qualitative, unscored)",
        "",
    ]
    refusals = 0
    t_total = time.monotonic()
    for i, (category, question) in enumerate(QUESTIONS, start=1):
        t0 = time.monotonic()
        result = ask(question, retriever, llm, k=k)
        dt = time.monotonic() - t0
        refusals += result.refused
        cites = (
            "; ".join(
                f"[{c.index}] {c.part}" + (f" p.{c.page}" if c.page else "")
                for c in result.citations
            )
            or "—"
        )
        lines += [
            f"## Q{i:02d} ({category}) — {dt:.0f}s",
            "",
            f"**Q:** {question}",
            "",
            f"**A:** {result.answer}",
            "",
            f"**Cited:** {cites}",
            "",
        ]
        status = "REFUSED" if result.refused else "answered"
        typer.echo(f"  Q{i:02d} [{category}] {status} {dt:.0f}s")

    lines += [
        "---",
        "",
        f"Total: {len(QUESTIONS)} questions, {refusals} refusals, "
        f"{time.monotonic() - t_total:.0f}s wall time.",
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")
    typer.echo(f"wrote {out}")


if __name__ == "__main__":
    app()
